server:
  port: 8181
keycloak:
  enabled: true
  realm: OMS-keyclock
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: Keycloak-demo
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  security-constraints:
    - auth-roles:
      - User
      security-collections:
      - name: unsecured
        patterns:
        - /keycloak
    - auth-roles: 
      - Admin
      security-collections:
      - name: secured
        patterns:
        - /v1/admin
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
